repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
        args: [
          "--unsafe",
          ]
    -   id: check-json
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md"
            ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
    -   id: ruff
    -   id: ruff-format
