repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
        args: [
          "--unsafe",
          ]
    -   id: check-json
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md"
            ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
    -   id: ruff

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black