ci:
    skip: [
        "poetry-lock",
    ]

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
        args: [
          "--unsafe",
          ]
    -   id: check-json
    -   id: trailing-whitespace
        args: [
            "--markdown-linebreak-ext=md"
            ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
    -   id: ruff-check
    -   id: ruff-format

-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
